name: archive
version: 1.0.25
author: Brendan Duncan <brendanduncan@gmail.com>
description: Provides encoders and decoders for various archive and compression formats such as zip, tar, bzip2, gzip, and zlib.
homepage: https://github.com/brendan-duncan/archive
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: https://github.com/brendan-duncan/archive/wiki
dependencies:
  crypto: '>=0.9.2 <3.0.0'
  args: '^0.13.5'
dev_dependencies:
  browser: '<1.0.0'
  test: '>=0.12.13 <1.0.0'
